### ISSUE TITLE
Season of the Hunt

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/d2-additional-info#196]
https://www.bungie.net/en/Explore/Detail/News/49675
- [X] Update README
- [X] Update d2-season-info.ts

Am I missing anything else?

**Comment by nev-r** [comment]
https://github.com/DestinyItemManager/d2-additional-info/blob/master/output/season-tags.json

**Comment by delphiactual** [comment]
https://www.bungie.net/en/Explore/Detail/News/49722

```
Soft Cap: 1200 
Hard Cap: 1250 
Pinnacle Cap: 1260 
```
