### ISSUE TITLE
Special Ammo Grenade Launcher

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/d2-additional-info#208]
As far as bounties are concerned Special Ammo Grenade Launcher https://data.destinysets.com/i/InventoryItem:2467068281 should only match field forged grenade launchers not heavy grenade launchers

**Comment by bhollis** [comment]
We'll need to "invent" a fake InventoryItemCategory for it

**Comment by delphiactual** [comment]
153950757-335733929 ?
GL-Special Ammo

https://data.destinysets.com/i/Objective:335733929

**Comment by delphiactual** [comment]
possibly same for slug shotguns
