### ISSUE TITLE
Rich Text

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/d2-additional-info#209]
Rich Texts do not seem to work in Milestones or Quests.

![image](https://user-images.githubusercontent.com/4798491/99992548-b7055100-2d73-11eb-989f-c0975bfc0da9.png)

New Rich Text needed as well for `Lost Sector`
![image](https://user-images.githubusercontent.com/4798491/99992615-c97f8a80-2d73-11eb-89ae-2b090504c237.png)

EDIT: `Stasis` is likely missing due to no current svg

**Comment by nev-r** [comment]
re: edit: same with lost sector afaik

the BL font is out there, just praying tom or someone will do an svg conversion

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/tree/new-rich-texts

I added the lost sector svg to no avail here

**Comment by delphiactual** [comment]
![image](https://user-images.githubusercontent.com/4798491/101537590-fc6f7400-3958-11eb-871f-ea4c59477ff3.png)

@nev-r It appears we also need to apply richText to `displayProperties.description` as well.

**Comment by nev-r** [comment]
more the merrier
