### ISSUE TITLE
make `source:events` an alias for the already curated `is:dawning or is:crimsondays or is:solstice or is:fotl or is:revelry or is:games` filters

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/d2-additional-info#255]
as the event info has already been more thoroughly pulled apart, I would like to figure out a way to make a source, by way of combining search filters...

similarly `source:raid` could be changed to `source:crownofsorrow or source:deepstonecrypt or source:eow or source:garden or source:lastwish or source:leviathan or source:scourge or source:sos`

**Comment by TMMania** [comment]
Source:DCV

"DCV" meaning the Destiny Content Vault. Identifies items from activities that are currently in the Destiny Content Vault.

**Comment by delphiactual** [comment]
`source:raid`, does work. just trying to make this more adaptable.
