### ISSUE TITLE
vigilance wing catalyst icon broken...

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/d2-additional-info#288]
![image](https://user-images.githubusercontent.com/4798491/134788741-f8c6e516-a036-437a-a64e-1a771eac1d96.png)

**Comment by delphiactual** [comment]
Correct Url: `https://www.bungie.net/common/destiny2_content/icons/1d38c8d82f1bd1d22bf76314fe8764f9.jpg`
Referred:     `https://www.bungie.net/common/destiny2_content/icons/1d38c8d82f1bd1d224d8b3b4fe8764f9.jpg`

looks like a build issue on DIM side

**Comment by nev-r** [comment]
so here, `bf7631 -> 4d8b3b`
in DIM previously, `230660 -> b13b84`

it continues to seem like things that look like color codes are being scrambled during build

**Comment by delphiactual** [comment]
no longer broken in current build
