### ISSUE TITLE
Generate String Vars

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/d2-additional-info#449]
Generate a listing of string vars

**Comment by nev-r** [comment]
makes sense. someone said it can be pulled from a public progressions profile without oauth

**Comment by nev-r** [comment]
but a lot of it will be personalized like material counts

**Comment by robojumper** [comment]
Could grab two or more different active profiles and assume that if a variable has different values between the profiles, it's almost certainly personalized. Could result in a lot of churn after new content relase though when every account has the same starting value...
