### ISSUE TITLE
Slim down seasons data

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/d2-additional-info#471]
[Calculating the season of items](https://github.com/DestinyItemManager/DIM/blob/e6ae335774a41a1243c0ac136c51183b66785f69/src/app/inventory/store/season.ts#L28) pulls in some very large JSON into the initial bundle. While there's work we could (and should) do to lazy load this info, it'd also be great if we could slim down that info significantly - for example, by not populating season data for items where we can get their season from the overlay.

**Comment by delphiactual** [comment]
we already do this...

https://github.com/DestinyItemManager/d2-additional-info/blob/master/src/generate-season-to-source.ts#L130-L164

DIM never loads seasons_unfiltered.json

**Comment by bhollis** [comment]
I'm not sure that filtering is enough. What I see there is that we filter out items without any `displayVersionWatermarkIcons` (which I think filters out *too much*, see below, we should be OK if there's a `iconWatermark` or `iconWatermarkShelved` as well, or if the current version has a watermark even if some other versions are empty). We also filter out items that we can figure out from source, and filter items from some specific categories and whatnot.

But check out how we look up seasons in DIM:

https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/store/season.ts#L42-L47:

We get the icon overlay:
```ts
const iconOverlay =
      (currentVersion !== undefined &&
        asDef.quality?.displayVersionWatermarkIcons?.[currentVersion]) ||
      asDef.iconWatermark ||
      asDef.iconWatermarkShelved ||
      undefined;
```

https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/store/season.ts#L69-L72

Then we use the overlay and source to find the season. Here it is refactored to be a bit more straightforward:
```
  if (overlay) {
    return (
      D2SeasonFromOverlay[overlay] ||
      D2SeasonBackup[hash]
    );
  }

  if (source && source in SourceToD2Season) {
    return SourceToD2Season[source];
  }

  return D2Season[hash] || D2CalculatedSeason;
```

Effectively:

1. If there's an overlay:
    2. If there's a record in `watermark-to-season.json` (48 watermarks) for that overlay, use it
    3. Otherwise look in `seasons_backup.json` (1,203 items) by item hash
1. If there's a source, and we have its source in `season-to-source.json` (349 sources), use the data from there. (I think this should be called `source-to-season.json`)
2. Look in `seasons.json` (5,651 items) by item hash
3. Fall back to current season

What I'm suggesting is:

1. If an item definition contains a watermark, via `displayVersionWatermarkIcons` or `iconWatermark` or `iconWatermarkShelved`, and that watermark can be associated with a season, that hash should not be in `seasons.json` because we won't bother using it.
2. If the remaining items after step 1 do not include one of the sources in `source-to-season.json`, that source should be removed from `source-to-season.json`.
3. `seasons_backup.json` should be removed in favor of `seasons.json`
4. Rework the season-detection logic in DIM to look in `watermark-to-season.json`, then fall back to `source-to-season.json`, then fall back to a very trimmed-down `seasons.json` that only contains hashes that could ever get to this level of fallback.
