### ISSUE TITLE
Font submodule bump doesn't re-generate font glyphs enum

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/d2-additional-info#493]
Updates like #491 ought to add the new enum entries (here the `strand_hunter_buzzsaw` enum entry) automatically and copy the font to output (manually regenerated in #492).

**Comment by delphiactual** [comment]
https://github.com/dependabot/fetch-metadata/issues/111

**Comment by delphiactual** [comment]
Bonus, only run `generate:glyph-enums` here and save `12s` each run

**Comment by delphiactual** [comment]
fixed by #524
