### ISSUE TITLE
Don't duplicate info for aliases in output/missing-source-info.ts

### ISSUE THREAD

**Issue by robojumper** [DestinyItemManager/d2-additional-info#507]
Interesting, I didn't realize that the aliases cause the hashes to be repeated. Feels like an opportunity?

_Originally posted by @bhollis in https://github.com/DestinyItemManager/d2-additional-info/pull/506#discussion_r1354056862_

**Comment by bhollis** [comment]
These are also repeated in `source-info.ts` - each of, for example `itl`, `intothelight`, and `brave` contain the exact same object.
