### ISSUE TITLE
categorize new exotics, vex offensive armor/weapons

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/d2-additional-info#61]
maybe include season pass?

**Comment by delphiactual** [comment]
yes

**Comment by sundevour** [comment]
i think maybe seasonpass: will end up being if(vexoffensive||season9versionofvexoffensive||season10etc)

**Comment by delphiactual** [comment]
maybe make a file `source\unused.json` that lists all sources that do not have a current category association.

**Comment by delphiactual** [comment]
closed by #66
