### ISSUE TITLE
sort mods

### ISSUE THREAD

**Issue by sundevour** [DestinyItemManager/d2-additional-info#65]
like ghost categories, lets identify armor mods by
• purpose ("load", "ammo finder", "unflinching")
• enhancedness
• weapon affinity

this isn't hugely useful but would mean we can sort/group mods page, mods socket popup, and potentially loadout builder options, in a far more useful way than d2.exe currently does

**Comment by delphiactual** [comment]
stackable

**Comment by delphiactual** [comment]
failureMessage with array of mods they apply to, basically our own hash table for failureMessages
